# This is the name of the workflow that will appear in the Actions tab
name: Deploy Portfolio to GitHub Pages

# Define when the workflow should run
on:
  push:                   # Run the workflow whenever there's a push...
    branches:
      - main              # ...to the main branch
  workflow_dispatch:      # Allow manual trigger from GitHub UI

# Set required permissions for deployment
permissions:
  contents: read          # Allow the action to read the repository contents
  pages: write            # Allow the workflow to write to GitHub Pages
  id-token: write         # Required for authentication with GitHub Pages

# Define the job(s) to run
jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner provided by GitHub

    steps:
      # Step 1: Checkout the source code from your repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # Step 2: Setup GitHub Pages deployment environment
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      # Step 3: Upload the static files (HTML, CSS, JS) as an artifact
      - name: Upload static site files
        uses: actions/upload-pages-artifact@3.0.1
        with:
          path: .           # Use "." if your index.html is in the root folder

      # Step 4: Deploy the uploaded artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
